### PR TITLE
remove init of router which causes the testsuite to fail

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by robertkowalski** [comment]
still one failing test but at least one more green

**Comment by robertkowalski** [comment]
should be all green now

**Comment by robertkowalski** [comment]
regarding the last test: not a big fan of it as it is very tightly coupled to the inner workings of a store - maybe we should just delete it

**Comment by benkeen** [comment]
Thanks @robertkowalski.

**Pull request merged**
